### ISSUE TITLE
Recommend JS design patterns over others

### ISSUE THREAD

**Issue by maxf** [alphagov/gds-way#105]
Should we go further and tackle the problem of JavaScript having so many ways to write things? Not just at the commonjs level, but also things like `=>` vs `function`, `class` vs `function`, `for` vs `forEach` vs `map`, Promises vs `async`/`await`, TypeScript vs Flow, etc.

Every other language has the same issue, of course. But JS happens to be worse, and this can result in code being very hard to read and modify by devs inheriting a JS codebase (which is the main problem the GDS Way is trying to solve, I think). And I'm not even talking about packages like Ramda that let you write your JS in an almost unintelligible way for people not used to pure functional programming or other paradigms. Should we encourage some of those practices and reject others?

I'm afraid I don't have a PR that answers this, but I think an extra conversation about higher-level abstract patterns is worth having.

**Comment by nickcolley** [comment]
Not a comment about what style of JavaScript we recommend but a proposal for the upper limit of new JavaScript features we support.

I'd propose the following:

- Avoid [stage-3 candidates](https://babeljs.io/docs/plugins/preset-stage-3/) and below
- Track the V8 version in the LTS Node.js release

This means avoiding transpiling entirely, and use only features natively available.

See https://zeit.co/blog/next#data-fetching-is-up-to-the-developer

"Our stance of what features we transpile (like async/await) can be summed up as: we target V8's capabilities. Since our goal is code-sharing between server and client, this gives us great performance when executing the code on Node and developing on Chrome or Brave, for example."

**Comment by nickcolley** [comment]
In terms of actual style, I'd propose that we use the more immutable functional methods for data manipulation where possible.

Making use of ES5 .map() .filter() .reduce() .concat() .

Related:
- https://eloquentjavascript.net/1st_edition/chapter6.html
- http://cryto.net/~joepie91/blog/2015/05/04/functional-programming-in-javascript-map-filter-reduce/

**Comment by jonheslop** [comment]
We definitely need to expand the Node.js style guide to have a section on preferred JavaScript coding styles.

@Nooshu shared [this link to a repo of best practices](https://github.com/i0natan/nodebestpractices) a couple of weeks back and we could just wholesale appropriate a lot of it as our own opinions.

We could enforce these opinions with an _even_ more opinionated linter than [Standard](https://standardjs.com/) such as [xo](https://github.com/sindresorhus/xo).

For instance xo prefers `const` over `var` (unless a `let` is appropriate) and also `=>` vs `function`.

Right now on Pay we’re still on node 6.11.12 so we’re not doing any `async/await` stuff so I dunno what we’d say about that stuff.

**Comment by maxcbc** [comment]
I can't find the article now, it was by Google or Mozilla. 
But their argument for writing `async/await` was that they intend to optimise the implementation heavily in future so while it may be slower now, in future it will be the fastest way to handle async.

**Comment by maxf** [comment]
I think I'll try and write something up, maybe during the next firebreak.

**Comment by danielroseman** [comment]
Max's PR was merged, closing.
