### ISSUE TITLE
Investigate whether a tool exists that can do both availability monitoring and user journey testing.

### ISSUE THREAD

**Issue by techforevil** [alphagov/gds-way#15]

**Comment by techforevil** [comment]
@alexmuller @rjw1 do we have anything on this?

**Comment by whpearson** [comment]
Pingdom can do things like this. 

However on all the teams that I've been on we don't tend to use it for user journey testing as it is easier to use the user journey testing code that we develop as part of our continuous integration (and can be run locally). So it is consistent.

So that is a important consideration.

**Comment by nickcolley** [comment]
Something to consider: https://www.iteratec.de/tech-blog/artikel/news/enabling-webpagetest-to-test-complete-customer-journeys-1/

**Comment by stephenharker** [comment]
Transferred to Trello
