### ISSUE TITLE
Re: 'Programming languages'

### ISSUE THREAD

**Issue by freesteph** [alphagov/gds-way#403]
Ruby is mentioned 3rd in the list of backend programming languages we use, and doesn't have an actual section dedicated to it. This makes it seem like an odd choice, when it is our number one language. I think it's important we reflect that in the guide.

Problem with 'Programming languages' (https://gds-way.cloudapps.digital/standards/programming-languages.html)

**Comment by louzoid-gds** [comment]
Hi freesteph!
Ruby doesn't have a section dedicated because the other langs have specific guidance under them e.g. use python 3. If you think there is something specific here we should be adding regarding Ruby, please do raise a PR but bear in mind we have some basics in the [Style guides](https://gds-way.cloudapps.digital/manuals/programming-languages.html) section.
