### ISSUE TITLE
Markdown guidance

### ISSUE THREAD

**Issue by OllieJC** [alphagov/gds-way#657]
Following a discussion with @jamietanna [here](https://github.com/alphagov/gds-way/pull/655), should we have some guidance around markdown, even if that's to say no preferences around usage?

I'm in favour of setting a max line length and using breaks within a sentence as I find it makes using the terminal and comparing changes in commits easier, but I do appreciate that's not easy to maintain with some editors including GitHub's web interface and some parsers/renderers handle differently. So, I'd happily follow guidance saying not to break sentences if it was noted and included somewhere, or maybe we note that there's no set guide as long as the output renders correctly?

**Comment by jamietanna** [comment]
Per my comment, I'd prefer that its not broken up, because then it allows i.e. the user's text editor to break it as appropriate, for instance if they need it to be broken at different limits to improve accessibility, as well as generally, I find it easier to read / edit when it doesn't need to be manually chopped and changed

**Comment by kevindew** [comment]
@benthorner I remember this seem debate coming up in GOV.UK and us coming to an agreement (no max line lengths) do you know if that was documented anywhere? I wonder if it can feed into this

**Comment by benthorner** [comment]
@kevindew I remember a discussion but not the context or the outcome, unfortunately. I thought it was in a PR but it might have been Slack. I've had a look at a load of PRs and can't see anything about it.

@OllieJC could you clarify what this issue is about? Is it about commit / PR messages, or anywhere we write Markdown e.g. READMEs?

Personal take: don't break lines manually except in commit / PR messages. Those two exceptions are partly out of habit, but they also seem to be the default behaviour of Vim, so let's go with the flow there.

In support of no line breaks: we force it (automatically) on code (on GOV.UK), so we shouldn't force it with Markdown either.

**Comment by louzoid-gds** [comment]
@OllieJC any additional thoughts on this? 
We could add a page to the Style guides section if we think it will be useful to teams. If not, I'll close the issue
